In [21]:
#code5-33
import pandas as pd

import optuna
from optuna.integration import OptunaSearchCV
from optuna.distributions import FloatDistribution
from optuna.distributions import IntDistribution


dataset='chap5_2.csv'
df=pd.read_csv(dataset)

In [26]:
import numpy as np
import pandas as pd

from pmdarima.model_selection import train_test_split

from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error

import optuna
from optuna.integration import OptunaSearchCV
from optuna.distributions import FloatDistribution
from optuna.distributions import IntDistribution

import warnings
warnings.simplefilter('ignore')

import matplotlib.pyplot as plt
plt.style.use('ggplot') #グラフスタイル
plt.rcParams['figure.figsize'] = [12, 9] #グラフサイズ
plt.rcParams['font.size'] = 14 #フォントサイズ

In [27]:
dataset='chap5_2.csv'
df=pd.read_csv(dataset)
df

,date,day_of_the_week,y1,y21,y22,x1,x2,x3,x4,holiday
0,2016/6/6,Mon,818979,177,4627,18.3,0.0,0.006,0,0
1,2016/6/7,Tue,789332,164,4813,19.8,0.9,0.002,0,0
2,2016/6/8,Wed,793266,141,5626,22.8,0.5,0.002,0,0
3,2016/6/9,Thu,721415,157,4595,23.1,7.0,0.005,0,0
4,2016/6/10,Fri,796138,146,5453,22.2,0.0,0.003,0,0
...,...,...,...,...,...,...,...,...,...,...
136,2016/10/20,Thu,799006,158,5052,20.8,0.0,0.002,0,0
137,2016/10/21,Fri,822875,145,5687,17.8,0.5,0.007,0,0
138,2016/10/22,Sat,1326138,142,9433,17.7,82.9,0.229,7500,1
139,2016/10/23,Sun,1392365,155,9087,16.9,76.5,0.225,7500,1
140,2016/10/24,Mon,689187,107,6403,17.3,10.8,0.010,0,0

In [17]:
pip install pmdarima

Collecting pmdarima
  Downloading pmdarima-2.0.3-cp310-cp310-win_amd64.whl (569 kB)
     -------------------------------------- 569.7/569.7 kB 9.0 MB/s eta 0:00:00
Requirement already satisfied: statsmodels>=0.13.2 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pmdarima) (0.13.5)
Requirement already satisfied: joblib>=0.11 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pmdarima) (1.1.1)
Collecting Cython!=0.29.18,!=0.29.31,>=0.29
  Downloading Cython-0.29.36-py2.py3-none-any.whl (988 kB)
     -------------------------------------- 988.3/988.3 kB 6.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.2 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pmdarima) (1.23.5)
Requirement already satisfied: scikit-learn>=0.22 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pmdarima) (1.2.1)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pmdarima) (65.6.3)
Requirement already satisfied: pandas>=0.19 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pmdarima) (1.5.3)
Requirement already satisfied: scipy>=1.3.2 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pmdarima) (1.10.0)
Requirement already satisfied: urllib3 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pmdarima) (1.26.14)
Requirement already satisfied: pytz>=2020.1 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pandas>=0.19->pmdarima) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from pandas>=0.19->pmdarima) (2.8.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from scikit-learn>=0.22->pmdarima) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from statsmodels>=0.13.2->pmdarima) (22.0)
Requirement already satisfied: patsy>=0.5.2 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from statsmodels>=0.13.2->pmdarima) (0.5.3)
Requirement already satisfied: six in c:\users\yoshikoshi\anaconda3\lib\site-packages (from patsy>=0.5.2->statsmodels>=0.13.2->pmdarima) (1.16.0)
Installing collected packages: Cython, pmdarima
Successfully installed Cython-0.29.36 pmdarima-2.0.3
Note: you may need to restart the kernel to use updated packages.

In [19]:
pip install optuna

Collecting optuna
  Downloading optuna-3.2.0-py3-none-any.whl (390 kB)
     -------------------------------------- 390.6/390.6 kB 3.0 MB/s eta 0:00:00
Collecting colorlog
  Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: numpy in c:\users\yoshikoshi\anaconda3\lib\site-packages (from optuna) (1.23.5)
Collecting alembic>=1.5.0
  Downloading alembic-1.11.1-py3-none-any.whl (224 kB)
     -------------------------------------- 224.5/224.5 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: PyYAML in c:\users\yoshikoshi\anaconda3\lib\site-packages (from optuna) (6.0)
Requirement already satisfied: sqlalchemy>=1.3.0 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from optuna) (1.4.39)
Requirement already satisfied: tqdm in c:\users\yoshikoshi\anaconda3\lib\site-packages (from optuna) (4.64.1)
Requirement already satisfied: packaging>=20.0 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from optuna) (22.0)
Collecting cmaes>=0.9.1
  Downloading cmaes-0.9.1-py3-none-any.whl (21 kB)
Requirement already satisfied: typing-extensions>=4 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna) (4.4.0)
Collecting Mako
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     ---------------------------------------- 78.7/78.7 kB 4.3 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from sqlalchemy>=1.3.0->optuna) (2.0.1)
Requirement already satisfied: colorama in c:\users\yoshikoshi\anaconda3\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\yoshikoshi\anaconda3\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.1)
Installing collected packages: Mako, colorlog, cmaes, alembic, optuna
Successfully installed Mako-1.2.4 alembic-1.11.1 cmaes-0.9.1 colorlog-6.7.0 optuna-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [28]:
#code5-34
#曜日のダミー変数を生成
week_list=['Tue','Wed','Thu','Fri','Sat','Sun','Mon']

enc=OneHotEncoder(categories=[week_list],sparse=False)

week_d=enc.fit_transform(df[['day_of_the_week']])

df_week_d=pd.DataFrame(week_d,index=df.index,columns=week_list,dtype='int')
print(df_week_d)

     Tue  Wed  Thu  Fri  Sat  Sun  Mon
0      0    0    0    0    0    0    1
1      1    0    0    0    0    0    0
2      0    1    0    0    0    0    0
3      0    0    1    0    0    0    0
4      0    0    0    1    0    0    0
..   ...  ...  ...  ...  ...  ...  ...
136    0    0    1    0    0    0    0
137    0    0    0    1    0    0    0
138    0    0    0    0    1    0    0
139    0    0    0    0    0    1    0
140    0    0    0    0    0    0    1

[141 rows x 7 columns]

In [29]:
#code5-35
df = pd.concat([df, df_week_d], axis=1)
print(df) #確認

           date day_of_the_week       y1  y21   y22    x1    x2     x3    x4  \
0      2016/6/6             Mon   818979  177  4627  18.3   0.0  0.006     0
1      2016/6/7             Tue   789332  164  4813  19.8   0.9  0.002     0
2      2016/6/8             Wed   793266  141  5626  22.8   0.5  0.002     0
3      2016/6/9             Thu   721415  157  4595  23.1   7.0  0.005     0
4     2016/6/10             Fri   796138  146  5453  22.2   0.0  0.003     0
..          ...             ...      ...  ...   ...   ...   ...    ...   ...
136  2016/10/20             Thu   799006  158  5052  20.8   0.0  0.002     0
137  2016/10/21             Fri   822875  145  5687  17.8   0.5  0.007     0
138  2016/10/22             Sat  1326138  142  9433  17.7  82.9  0.229  7500
139  2016/10/23             Sun  1392365  155  9087  16.9  76.5  0.225  7500
140  2016/10/24             Mon   689187  107  6403  17.3  10.8  0.010     0

     holiday  Tue  Wed  Thu  Fri  Sat  Sun  Mon
0          0    0    0    0    0    0    0    1
1          0    1    0    0    0    0    0    0
2          0    0    1    0    0    0    0    0
3          0    0    0    1    0    0    0    0
4          0    0    0    0    1    0    0    0
..       ...  ...  ...  ...  ...  ...  ...  ...
136        0    0    0    1    0    0    0    0
137        0    0    0    0    1    0    0    0
138        1    0    0    0    0    1    0    0
139        1    0    0    0    0    0    1    0
140        0    0    0    0    0    0    0    1

[141 rows x 17 columns]

In [35]:
#csv へdfを書き込み
#data_file='chap5_2.csv'
df.to_csv('chap5_2.csv')