In [1]:
#000 ここから回帰分析開始して時間短縮-----20231001-----
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

#docker のときは/workdir/ を追記する
New_data_dir='/workdir/Num_3_predict/01_output/challenge_5'

import glob
Num_3_file=os.path.join(New_data_dir,'/workdir/Num_3_predict/01_output/challenge_5/df_2018_2024.csv')
Num_3_paths=glob.glob(Num_3_file)
display(Num_3_paths)

['/workdir/Num_3_predict/01_output/challenge_5/df_2018_2024.csv']

In [2]:
#001 csv_data 呼び出して確認
New_data_dir='/workdir/Num_3_predict/01_output/challenge_5'
Num_3_predict_dir=os.path.join(New_data_dir)
Num_3_file='df_2018_2024.csv' #西暦ごとに出力 + #005欠損値も確認
df=pd.read_csv(os.path.join(Num_3_predict_dir,Num_3_file))
display(df)

,Lottery_result,num_0,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,...,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10,Next_result
0,858,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,384
1,384,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,976
2,976,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,930
3,930,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,634
4,634,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,223
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1637,282,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,412
1638,412,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,271
1639,271,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,473
1640,473,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,186
1641,186,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,564

In [3]:
#002 最終行数を取得
last_row = df.shape[0] - 1#最終行番号
print(last_row)

last_row1 = df.shape[0]#0～最終までの行数
print(last_row1)

1641
1642

In [4]:
#003 説明変数と目的変数に分割-----まとめて出力できないか-----


# for i in range(0,1488): #スタートが0からで1つめ2つめ3つめで1つ値前まで　例(0,1280)なら1279まで、ひとつの数値でもOK、rows行番号でOk
for i in range(0,last_row1):  #0～最終までの行数
    
    X=df.iloc[:, :-1]
    y=df.iloc[:, -1]

    #モデルの構築と検証---"1"に近いと良い
    from sklearn.linear_model import LinearRegression
    model=LinearRegression()
    model.fit(X,y)
    # model.score(x,y)

    #学習
    from sklearn.model_selection import train_test_split
    # X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1→20→30→40 "本では42推奨しているけどここで調整するところ"
    #-----警告処置-----
    X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1→20→30　#微調整が必要かなsize=0.2→0.25→0.3　random_state= は20が基本で30→40で調整---42---
    model.fit(X_train,y_train)
    model.fit(X_test,y_test)


    x=X.iloc[i,:] #予測する行番号-----#003で列数確認
    y_pred=model.predict([x])[0]
    # y_pred

    y_pred=round(y_pred)
    print(i,y_pred)



    #予測値と比較
    # from sklearn.metrics import mean_squared_error
    # y=y.iloc[i,:]
    # score=mean_squared_error(y_pred,y)
    # print(score) 

    #100個で8分
    #1000個で95分
    #1482個で133分、211分、-----Max696m---朝は112m---ファンで冷やしながら90m----

#-----警告処置-----

0 471
1 177
2 416
3 800
4 422
5 596
6 497
7 484
8 559
9 382
10 478
11 430
12 327
13 92
14 657
15 704
16 415
17 477
18 386
19 546
20 214
21 861
22 678

In [ ]:
#004 完全一致率を算出----これで楽になるね
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

count=0
score=0
num=0

#for i in range(0,1488): #スタートが0からで1つめ2つめ3つめ1つ値前まで　例(0,1280)なら1279まで、rows行番号でOK
for i in range(0,last_row1):   #0～最終までの行数 
    
    y=df.iloc[i, -1]
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認
    y_pred=model.predict([x])[0]
    y_pred=round(y_pred)
    y_pred

    if y == y_pred:
        score += 1
    
        num = str(i)
    if num != '':
        count += 1
       
    # print(y,y_pred,num)
print('Total:', score,'/', count)

if count >= score:
    print(f'Perfect_matching = {score}/{count} ({score/count *100:.1f}%)')

In [ ]:
#ここでおわり

#-----大数の法則-----
#より500回くらいが目安？
#0.15 x 300 = 45回くらい？


#-----統計学てきに必要なサンプル数-----
#　確率分母　＝　1　/　勝率　　なので　必要な回数　＝　確率分母　ｘ　300（or 400）
#例　1 / 0.15 = 6.666　なので  6.666 x　300　＝　2000回分のサンプルがよい